# Generated by Django 5.2.5 on 2025-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('party_master_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('beat', models.CharField(max_length=50)),
                ('hul_code', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
